### ISSUE TITLE
Events files

### ISSUE THREAD

**Issue by qo4on** [uzh-rpg/rpg_timelens#11]
You wrote:
`A Google Colab notebook is now available here. You can upsample your own video and events from you gdrive.`
How to get events files and `timestamp.txt` for my own video?

**Comment by RobertLowe** [comment]
@danielgehrig18 yeah, how did you generate `timestamps.txt`? And create the `.npz` files?

Thanks!

**Comment by TashaSkyUp** [comment]
would love to know if the model checkpoint can be used to create high fps footage without having the event frames from a high speed camera?

**Comment by RobertLowe** [comment]
@TashaSkyUp my bet is probably not, DAIN is probably the best we'll get for now

**Comment by Zer0xPoint** [comment]
maybe there is a way to get timestamp file, because it just contains info of how long a frame takes to move to the next frame.

**Comment by danielgehrig18** [comment]
Hi all, this work uses a complementary event camera (not a high-speed camera), in addition to a standard camera. Instead of recording event frames it records an asynchronous stream of events, as can be observed in the video here: https://youtu.be/dVLyia-ezvo?t=56. For this reason, the method cannot work on images alone. The .npz files record the data that comes from an event camera. Each file contains a list of (x,y,t,p) which denote the position (x,y), time and sign of the brightness change measured by the event camera. Thus we also need to the know the timestamps of the images which are stored in the timestamp.txt file. For a regural video at say 30 FPS they can be calculated as i/30, where i is the frame index.
